yarn --dev add babel-plugin-dynamic-import-node
このbabelプラグインがないと、「import」を解決できずにエラーになる。

こんな感じのエラー
```
/Users/fukudayukihiro/RubymineProjects/onepage/frontend/tests/unit/specs/components/shopping/NavBar.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vuex from 'vuex';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
```